M48
; DRILL file {KiCad 8.0.7} date 2025-02-05T22:43:12+0100
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2025-02-05T22:43:12+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.7
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0236
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0941
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C0.1358
%
G90
G05
T1
X0.6241Y-0.8193
X0.6241Y-0.9768
T2
X3.6114Y-2.965
T3
X1.1102Y-2.965
X3.2835Y-2.335
M30
